#!/usr/bin/python3
#
# Copyright (c) 2021-2022 Orson Teodoro <orsonteodoro@hotmail.com>.  All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

def do_unroll_do_compression_asm():
	code_block= \
"	expand_message_blocks %d\n"
	print("/* Unrolled do_compression generated by gen_asm_unroll_message_expansion.py */")
	for j in range(16,64):
		print(code_block % (j), end="")

def do_unroll_do_compression_c():
	code_block= \
"	DO_MESSAGE_EXPANSION_ASM(%d);\n"
	print("/* Unrolled do_compression generated by gen_asm_unroll_message_expansion.py */")
	for j in range(16,64):
		print(code_block % (j), end="")

def main():
#	do_unroll_do_compression_asm()
	do_unroll_do_compression_c()

if __name__ == "__main__":
	main()
